### PR TITLE
fix kompose.image-pull-secret invalid when use compose configs

### PR DESCRIPTION
**Pull request by xingjianhui**
kompose version: 1.23.0 (bc7d9f4f)
compose version: 3.8

I found kompose.image-pull-secret will be invaild 
when compose service has configs

### CODE REVIEW

**Comment by xingjianhui** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

**Comment by hangyan** [comment]
@xingjianhui Can you add more description about the issue your PR is fixing? It's hard to understand based on your comment. May be some compose examples?

**Comment by xingjianhui** [comment]
If docker-compose set configs,
then use kompose convert command,
the output hello-deployment.yaml will be lose imagePullSecrets.

Example source docker-compose.yaml
`
version: "3.8"

configs:
  appconfig:
    file: ./test.yml

services:
  hello:
    image: busybox
    configs:
      - source: appconfig
        target: /etc/config/test.yml
    environment:
      - SOME_ENV=xxxx
    labels:
      - kompose.image-pull-secret=regcred
      - kompose.service.type=loadbalancer
 `

part of hello-deployment.yaml
`
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hello
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f test.yml convert
        kompose.image-pull-secret: regcred
        kompose.service.group: cdp
        kompose.service.type: loadbalancer
        kompose.version: 1.23.0 (bc7d9f4f)
      creationTimestamp: null
      labels:
        io.kompose.service: hello
    spec:
      containers:
        - env:
            - name: SOME_ENV
              value: xxxx
          image: busybox
          name: hello
          resources: {}
          volumeMounts:
            - mountPath: /etc/config/test.yml
              name: appconfig
              subPath: test.yml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: test.yml
                path: test.yml
            name: appconfig
          name: appconfig
status: {}
`
@hangyan

**Comment by hangyan** [comment]
codes look good. Please check the CI result for fix related issues @xingjianhui

**Comment by tk42** [comment]
@xingjianhui 
I found another. ```ImagePullSecrets``` in podSpec.go is called from nowhere. It should be also called from the indent inside ```MultipleContainerMode``` in kubernetes.go, otherwise images can’t be pulled with secret in ```--multiple-container-mode```.

**Comment by xingjianhui** [comment]
> @xingjianhui
> I found another. `ImagePullSecrets` in podSpec.go is called from nowhere. It should be also called from the indent inside `MultipleContainerMode` in kubernetes.go, otherwise images can’t be pulled with secret in `--multiple-container-mode`.

Hi, I found the problem so, and I found another problem when use `--multiple-container-mode` arg.
When use `--multiple-container-mode` to create a pod with mutiple containers, the out deployment will be lost all docker-compose configs.
So, I think fix `ImagePullSecrets` and `lose configs` within `--multiple-container-mode` need another PR

**Comment by xingjianhui** [comment]
> codes look good. Please check the CI result for fix related issues @xingjianhui

I fixed CI problem.

**Comment by hangyan** [comment]
@xingjianhui cla still failed

**Comment by hangyan** [comment]
@xingjianhui  still has ci issues

**Comment by xingjianhui** [comment]
> @xingjianhui still has ci issues

It exit 0 when i exec 
`golangci-lint run --out-format=github-actions --timeout 5m` on iTerm command line

**Comment by hangyan** [comment]
@xingjianhui  A local golangci script will be added soon

**Comment by hangyan** [comment]
@xingjianhui  Thanks for your contribution

**Pull request merged**
