### PR TITLE
add option --hostpaths

### PR DESCRIPTION
**Pull request by xiaoping378**
add option --hostpaths, #109

### CODE REVIEW

**Comment by cdrage** [comment]
Hey @xiaoping378 we're having the discussion here: https://github.com/kubernetes/kompose/issues/109 but we will go ahead and refactor --emptyvols to use --volumes :+1: when we do that you can update the above code to use the new parameter.

**Comment by surajnarwade** [comment]
@xiaoping378 , can you please rebase your PR

**Comment by cdrage** [comment]
Hey @xiaoping378 to comment on what @surajnarwade said, we added the CLI parameter --volumes. You will have to update your PR in order to add hostPath to `--volumes`.

**Comment by dtitov** [comment]
Any update?

**Comment by xiaoping378** [comment]
sorry, has no time to do this now.

**Comment by vikasgubbi** [comment]
any updates

**Pull request closed without merging**
