### PR TITLE
remove status field from generated yaml

### PR DESCRIPTION
**Pull request by shubhindia**
/kind feature
#### What type of PR is this?
Whenever the k8s yamls are generated, since status field is part of APIs, it is being added in the generated yamls, which is fine but should not be there since the objects are not applied yet.

#### What this PR does / why we need it:
This just adds a simple hack to remove the status field from generated yamls

#### Which issue(s) this PR fixes:
Fixes https://github.com/kubernetes/kompose/issues/975

### CODE REVIEW

**Review by AhmedGrati — COMMENTED** [review]
Thanks for the PR @shubhindia. I think removing the status should be okay, as it is not really needed. However, You should change the manifests in the e2e tests accordingly in order for the e2e tests to pass successfully. wdyt @cdrage?

**Comment by cdrage** [comment]
> Thanks for the PR @shubhindia. I think removing the status should be okay, as it is not really needed. However, You should change the manifests in the e2e tests accordingly in order for the e2e tests to pass successfully. wdyt @cdrage?

Yup! Fix the tests please and we can merge this in. I agree that we do not need status in the output.

**Comment by AhmedGrati** [comment]
ping @shubhindia

**Comment by shubhindia** [comment]
Acknowledged @AhmedGrati . Will push the changes by Monday.

**Comment by shubhindia** [comment]
closed in favour of https://github.com/kubernetes/kompose/pull/1746

**Pull request closed without merging**
