### PR TITLE
Fix annotations missing for ingress

### LINKED ISSUE #1071: Labels not converted to annotations in ingress
If you have something like:

```yaml
version: '2'
services:
    web:
        labels:
            kompose.service.expose: dev.example.com
            kompose.service.expose.tls-secret: tls-secret
            kompose.service.type: clusterip

            kubernetes.io/ingress.class: nginx
            certmanager.k8s.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/rewrite-target: /
        ports:
            - '80:80'
```

the annotations related to the ingress controller are not present in the `Ingress` object (they're there in `Service` and `Deployment`).

### PR DESCRIPTION
**Pull request by hangyan**
migrated from #1076, fix #1071

### CODE REVIEW

**Comment by mbrodala** [comment]
Would you mind making a new relase with this change? This currently requires me to do some manual `kubectl` patching to apply the annotations which are actually present as `labels` in my `docker-compose.yml`.

**Comment by hangyan** [comment]
> Would you mind making a new relase with this change? This currently requires me to do some manual `kubectl` patching to apply the annotations which are actually present as `labels` in my `docker-compose.yml`.

I can merge this into master into a few hours. But do a release need another admin to invovle. Can you use the master build then?

**Comment by mbrodala** [comment]
I'd love to. Are there prebuilt binaries somewhere or do I need to build it myself?

**Comment by hangyan** [comment]
> I'd love to. Are there prebuilt binaries somewhere or do I need to build it myself?

Seems no for now, the readme page contains instucitons about how to build it from source. I will try to add few more PRs and informer our admin to do a Release ASAP. Sorry for the slowly processing of this PR. Welcome to @ me at the comment and notify me that this blocks your work. I will handle it ASAP.

**Comment by mbrodala** [comment]
No worries, I can always find a workaround. I love what you guys have created here. :-)

**Pull request merged**
