### PR TITLE
feat: integrate pre-commit hooks

### PR DESCRIPTION
**Pull request by AhmedGrati**
# Description
This pull request adds the pre-commit hooks, and fixes our files to comply with the checks integrated into the `pre-commit-config.yaml`.

### CODE REVIEW

**Comment by cdrage** [comment]
@AhmedGrati I think something may have messed up with the commit? Looks like it's making changes that aren't about the pre-commit hook

**Comment by AhmedGrati** [comment]
@cdrage Thank you for pointing out this. In fact, I added pre-commit hooks, and apply these pre-commit hooks to the files so that all checks can pass.

**Comment by cdrage** [comment]
> @cdrage Thank you for pointing out this. In fact, I added pre-commit hooks, and apply these pre-commit hooks to the files so that all checks can pass. Please LMK if you see that it's appropriate to push the pre-commit config without changing files.

Yeah, I think we should merge the other PR in first, then pre-commit files. But just waiting for the person to update his PR to remove the leftover JS files.

**Comment by AhmedGrati** [comment]
@cdrage I update it, can you review it please?

**Comment by cdrage** [comment]
LGTM!

**Pull request merged**
