### PR TITLE
Add kompose.image-pull-secret

### LINKED ISSUE #897: Allow specifying imagePullSecret
Hi there,

How would one go about providing the `imagePullSecret` key to a `deployment`?

This could possibly help with #893 ? This might also be part of a broader discussion about "template-supported conversions", which would allow to make custom changes to the conversion outputs...

Cheers,

Jun

### PR DESCRIPTION
**Pull request by mikesimos**
fixes #897

### CODE REVIEW

**Comment by hangyan** [comment]
@cdrage

**Comment by cdrage** [comment]
@hangyan @mikesimos 

I'm not opposed nor am I accepting of this. It's a tough decision.

In one case, we support imagePullSecrets but we *dont* support secrets.

The other case is the fact that this is a good intermediary step..

In my opinion, I believe we should delay this PR until #296 is completed. Kompose is meant to transition people whom are complete noobies to Kubernetes. Adding a label that supports image-pull-secrets but not explaining that you have to add secrets before-hand isn't very Kompose-like.

@hangyan is right. It's not great to merge this now, but once #296 is completed, I'd be 100% for this.

**Comment by mikesimos** [comment]
OK! Having imagePullSecrets functionality upstream would be great. Thanks both!

**Comment by cdrage** [comment]
Hey @mikesimos does your PR here: https://github.com/kubernetes/kompose/pull/1040 override / close this one?

**Comment by mikesimos** [comment]
Closing as #1040 overrides this. Thanks!

**Pull request closed without merging**
