### PR TITLE
add networkmode service:

### PR DESCRIPTION
**Pull request by sosan**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
adjusting the network mode of services in docker compose (services:) and generate a mapping of deployments based on the network mode of each service merging containers into the destination deployment, and removing transferred deployments

compose.yaml example:

```
version: '3'

services:
  client:
    image: busybox
    command: ["sleep", "infinity"]
    container_name: threats-client
    restart: unless-stopped
    ports:
      - '8080:8080'

  server:
    image: busybox
    command: ["sleep", "infinity"]
    container_name: threats-server
    restart: unless-stopped
    network_mode: service:client
```
converted to add two container inside client-deployment:

```
....
 spec:
      containers:
        - args:
            - sleep
            - infinity
          image: busybox
          name: threats-client
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
        - args:
            - sleep
            - infinity
          image: busybox
          name: threats-server
      restartPolicy: Always
```

#### Which issue(s) this PR fixes:

Add feature commented in #1846

### CODE REVIEW

**Comment by sosan** [comment]
added e2e and more tests

**Review by cdrage — APPROVED** [review]

**Comment by cdrage** [comment]
@sosan looks like a failed test sorry, need it updated again :( I merged too many other PR's haha

**Comment by sosan** [comment]
> @sosan looks like a failed test sorry, need it updated again :( I merged too many other PR's haha

no problem

**Pull request merged**
