### PR TITLE
Add flag to turn off push image when kompose up

### PR DESCRIPTION
**Pull request by hangyan**

### CODE REVIEW

**Comment by hangyan** [comment]
fix #1105

**Comment by jdbohrman** [comment]
Lmao just when I run into an issue that this would have resolved.

**Comment by hangyan** [comment]
@jdbohrman you can build the binary from the source code in my repo if you are in a hurry

**Comment by orkenstein** [comment]
@hangyan thanks for the tip, i've been able to succesfully build & run `kompose` from this PR.
However, on `kompose up` I get this error:
```bash
FATA Error while deploying application: Get http://localhost:8080/api: dial tcp [::1]:8080: connect: connection refused
```
Any chance to avoid this?

**Comment by hangyan** [comment]
@orkenstein unfortunately this issue is not a easy one , the upstream library we use seems does not allow us to change the target port, or it’s possible, but need a lot of time to figured out. Normally Kubernetes will listen on 8080 as an unsecure port, but may be the latest versions has disable it by default.You can check the command args of the apiserver binary, i think it has a flag to enable this. I’m trully sorry for the inconvenience

**Comment by orkenstein** [comment]
@hangyan, ah, now worries. I'd better wait for the release of this feature. Hope it happens soon...

**Comment by orkenstein** [comment]
@cdrage, @containscafeine, could you please review this & merge this?

**Comment by orkenstein** [comment]
@hangyan @cdrage @containscafeine, hope you get some time to finish this PR.
Thanks

**Comment by cdrage** [comment]
Eh! This actually looks pretty good.

/lgtm
/approve

**Pull request merged**
