### PR TITLE
Variable name should not be the same as imported package name

### PR DESCRIPTION
**Pull request by hangyan**

### CODE REVIEW

**Comment by hangyan** [comment]
@surajnarwade @cdrage CI seems unstable..

**Comment by cdrage** [comment]
@hangyan Yeah, looks like the Fedora build system went down temporarily. I've gone ahead and restarted the build.

**Comment by hangyan** [comment]
@cdrage  how do i re-trigger the build?

**Comment by cdrage** [comment]
@hangyan If you do a force update, it can re-trigger the build (for example, using `git commit --amend` and amending the message and updating the PR).

I've triggered a rebuild manually however..

**Comment by hangyan** [comment]
@cdrage CI passed

**Pull request merged**
