### PR TITLE
Add Labels for CronJob https://github.com/kubernetes/kompose/issues/1795

### PR DESCRIPTION
**Pull request by realgam3**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Add CronJob  Labels:
* `kompose.controller.type`: cronjob
  * `kompose.cronjob.schedule`: "5 4 * * *"
  * `kompose.cronjob.concurrency_policy`: (Allow|Forbid|Replace)

#### Which issue(s) this PR fixes:
Feature https://github.com/kubernetes/kompose/issues/1795

### CODE REVIEW

**Comment by cdrage** [comment]
> @AhmedGrati @cdrage Because of the many conflicts I've decided to create a new Pull request,
> 
> I hope it's ok with you...

Fine by me!

**Comment by cdrage** [comment]
> > @AhmedGrati @cdrage Because of the many conflicts I've decided to create a new Pull request,
> > I hope it's ok with you...
> 
> Fine by me!

I'll go through the code once all the tests have pass & I have a bit of time tonight :)

**Comment by realgam3** [comment]
Thank you ❤️

**Comment by cdrage** [comment]
Approving and LGTM since this has been throughly reviewed a few times! Thanks for the awesome new feature!

I'll push a new release this week so this is out :)

**Comment by realgam3** [comment]
Thank you!
It was fun working with you.

**Pull request merged**
