### PR TITLE
Feat add ns generation

### LINKED ISSUE #1657: Specify a namespace with convert?
### What would you like to be added?

Hello,

I'm writing up some documentation on how to use Konvert with the OpenShift Developer Sandbox. However, when I convert my docker-compose file then run `oc apply -f`, I get a bunch of errors around the Deployment Config and a missing namespace.

Is there anyway to fix this during the `convert` process?

```
oc apply -f ocp/
persistentvolumeclaim/databasevolume created
persistentvolumeclaim/logvolume01 created
service/openemr configured
persistentvolumeclaim/sitevolume created
resource mapping not found for name: "mysql" namespace: "" from "ocp/mysql-deploymentconfig.yaml": no matches for kind "DeploymentConfig" in version "v1"
ensure CRDs are installed first
resource mapping not found for name: "mysql" namespace: "" from "ocp/mysql-imagestream.yaml": no matches for kind "ImageStream" in version "v1"
ensure CRDs are installed first
resource mapping not found for name: "openemr" namespace: "" from "ocp/openemr-deploymentconfig.yaml": no matches for kind "DeploymentConfig" in version "v1"
ensure CRDs are installed first
resource mapping not found for name: "openemr" namespace: "" from "ocp/openemr-imagestream.yaml": no matches for kind "ImageStream" in version "v1"
ensure CRDs are installed first
```

### Why is this needed?

We want to make this as easy possible for those convert docker-compose files to a Kubernetes namespace/OpenShift project.

### PR DESCRIPTION
**Pull request by AhmedGrati**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:
Implement namespace generation through the CLI flag `--namespace` or `-n`.

#### Which issue(s) this PR fixes:

Fixes #1657.

### CODE REVIEW

**Comment by cdrage** [comment]
Works for me! Thank you :)

**Review by cdrage — APPROVED** [review]

**Comment by MikeTangoEcho** [comment]
@AhmedGrati @cdrage Is there a way to disable this feature ? Or when there is no namespace specified it doesn't add all resources to `default` namespace. I use kompose with helm chart generation, and the namespace is decided on helm release installation.

The lines to be modified would be.

https://github.com/AhmedGrati/kompose/blob/608f87669f63a93c7af5700ee3d17bdbbf197256/pkg/transformer/utils.go#L465-L468

I can make a PR if needed.

**Comment by github-belhorma-bendebiche** [comment]
This is a breaking change. We currently create a namespace with other resources in it before installing the chart generated by kompose (and overriding the namespace using helm's flags). This flow is no longer possible: if we don't set a namespace, everything goes into `default`. If we do set a namespace, the chart is no longer installable (since the namespace already exists and we don't want the chart to create it).

**Comment by cdrage** [comment]
> This is a breaking change. We currently create a namespace with other resources in it before installing the chart generated by kompose (and overriding the namespace using helm's flags). This flow is no longer possible: if we don't set a namespace, everything goes into `default`. If we do set a namespace, the chart is no longer installable (since the namespace already exists and we don't want the chart to create it).

On it! This shouldn't of been added, sorry about that. I totally missed it.

**Comment by cdrage** [comment]
@github-belhorma-bendebiche Address in https://github.com/kubernetes/kompose/pull/1731

**Comment by github-belhorma-bendebiche** [comment]
Thank you for the quick fix!

**Pull request merged**
