### PR TITLE
Fix test-cmd errors

### PR DESCRIPTION
**Pull request by hangyan**
* fix stdin error
 * fix container name error
 * fix config load error

### CODE REVIEW

**Comment by hangyan** [comment]
fix #1148

**Comment by hangyan** [comment]
There are three porbelems:

1. #1141 introduces some test errors 
2. service config's file path become abs path now(does't know when and why,) breaks some tests
3. stdin support, the code and my local test is ok now, does't know it failed on traivs

**Comment by cdrage** [comment]
Woops.

Thanks for this fix!

/lgtm

**Comment by hangyan** [comment]
Does the lgtm label not working?

**Pull request closed without merging**
