### PR TITLE
Add kompose.image-pull-secret and kompose.image-pull-policy

### PR DESCRIPTION
**Pull request by mikesimos**

### CODE REVIEW

**Comment by cdrage** [comment]
Tests are written, we've gotten multiple different PR's for this (https://github.com/kubernetes/kompose/pull/1039). 

I think we should merge this in. At least until native secrets implementation is added.

What do you think @hangyan ?

**Comment by cdrage** [comment]
Including them here is fine @mikesimos ! I think that we should merge in these labels as they've been requested quite a bit. At least until `Secrets` is natively implemented, the labels is a good middle-ground. As well as coverage for version 1/2 of Docker Compose.

Just waiting for reviews from @hangyan and maybe @xianlubird

**Comment by xianlubird** [comment]
@mikesimos 
1. Maybe you should rebase these commits to one or two commits
2. How about compose v1 and v2
3. Until now, the PR is fine.

**Comment by mbana** [comment]
Awesome. Just what I was looking for.

Any ETA on when this might get merged into master?

**Comment by hangyan** [comment]
@mbana Secret can be added to the `default`  ServiceAccount in the same namespace,  check this out:
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account After this ,you do not need to specify the secret name in the deployment or pod, kubernetes will figure it out itself

**Comment by mbana** [comment]
I should have been more clear. I am waiting for the kompose.image-pull-policy feature.

**Comment by hangyan** [comment]
@mikesimos Beside cdrage's comment, others LGTM

**Comment by kiela** [comment]
@cdrage @hangyan Any chance to merge it and release as both of you said this feature can be shipped?

**Comment by cdrage** [comment]
When @mikesimos updates his PR / resolves conflicts I can take a look at the code and do a review. I don't see an issue anymore adding this :+1:

**Pull request closed without merging**
