### PR TITLE
Fix unset env bug for v3 compose

### LINKED ISSUE #918: "panic: runtime error: invalid memory address or nil pointer dereference" when using environment unset variables
when using a compose file containing an unset environment var, kompose crash with:
```
kompose up -f docker-compose.yml 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1621e4b]
```

example:
```
version: '3'

services:
  jenkins:
    image: jenkins
    environment:
      - DEBUG
```

Note: if the environment var is set, everything work as expected. example:
```
version: '3'

services:
  jenkins:
    image: jenkins
    environment:
      - DEBUG=1
```

### PR DESCRIPTION
**Pull request by hangyan**
fix #918

### CODE REVIEW

**Comment by cdrage** [comment]
Tests pass... is it possible to add a test? If not, I could quickly write one up 👍

**Comment by hangyan** [comment]
Sure, I will add some unit test

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hangyan** [comment]
@cdrage I have add some tests and check the docker-compose doc and find that my previous code is not correct. Link: https://docs.docker.com/compose/compose-file/#environment. I have rewrite the logic, please help me review it

**Comment by hangyan** [comment]
related to #892 . @cdrage

**Comment by cdrage** [comment]
These LGTM. Thanks for the contribution!!

**Pull request merged**
