### PR TITLE
Fix typos in Makefile

### LINKED ISSUE #971: Minor typos in Makefile
https://github.com/kubernetes/kompose/blob/39ad6140c33d35954aed38a66155f4ac392ce547/Makefile#L70-L71
Should probably be
```Makefile
.PHONY gen-cmd
gen-cmd:
```
and
https://github.com/kubernetes/kompose/blob/39ad6140c33d35954aed38a66155f4ac392ce547/Makefile#L129
Should probably be
```Makefile
.PHONY test-k8s
```

### PR DESCRIPTION
**Pull request by jaden-young**
Closes #971

### CODE REVIEW

**Comment by cdrage** [comment]
Hey @jaden-young thanks for the PR! Once you have signed the CLA we will be able to merge this :)

**Comment by jaden-young** [comment]
I've signed the CLA.

**Comment by hangyan** [comment]
@jaden-young Thanks for you contribution!

**Comment by hangyan** [comment]
@cdrage Seems there are some errors after merge this PR, i'm looking on it.

**Comment by jaden-young** [comment]
That's interesting, my apologies for not testing. Are/were there files living somewhere with the target names?

**Comment by hangyan** [comment]
@jaden-young It's weird, still looking on it.

**Comment by hangyan** [comment]
@cdrage Can you help restart the build or locate the error? Didn't find out why the build failed!

**Comment by cdrage** [comment]
Looks like CI passes now :+1: Odd that it did that!

**Pull request merged**
