### PR TITLE
Fix custom pvc size in v2 compose not working error

### LINKED ISSUE #927: kompose.volume.size label is not working
kompose.volume.size label is not working.
I tested on macOS 10.13.3 and brew installed kompose.

``` yaml
# test.yaml 
version: '2'
services:
  db:
    image: postgres:10.1
    labels:
      kompose.volume.size: 1Gi
    volumes:
      - db-data:/var/lib/postgresql/data
```

``` shell
$ kompose version
1.8.0 ()

$ ls
test.yaml

$ kompose convert -f test.yaml
INFO Kubernetes file "db-service.yaml" created
INFO Kubernetes file "db-deployment.yaml" created
INFO Kubernetes file "db-data-persistentvolumeclaim.yaml" created

$ ls
db-data-persistentvolumeclaim.yaml db-deployment.yaml db-service.yaml test.yaml

$ cat db-data-persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db-data
  name: db-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi # <-- not 1Gi
status: {}
```

### PR DESCRIPTION
**Pull request by hangyan**
fix #927

### CODE REVIEW

**Comment by cdrage** [comment]
Is it possible for you to add a unit test?

**Comment by cdrage** [comment]
Otherwise, LGTM

**Comment by hangyan** [comment]
Sure, I will add some test

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by surajnarwade** [comment]
LGTM

**Comment by cdrage** [comment]
Tests look good, thanks for the contribution! LGTM.

**Pull request merged**
