### PR TITLE
retrieve container test by updating Dockerfile

### PR DESCRIPTION
**Pull request by namusyaka**
`make test-image` and `make test-container` seem broken, is there any chance to recover these tasks?

### CODE REVIEW

**Comment by hangyan** [comment]
I thinks we can add it to the `.travis.yml` file.

**Comment by namusyaka** [comment]
Thanks for the review, @hangyan !
Since the current entrypoint of the Dockerfile runs [`make test`](https://github.com/kubernetes/kompose/blob/01f18cb3cf3f081b33c057f602e5f22345afb808/script/test_in_container/run.sh#L25), I don't think we need to add it to the travis integration.
I was thinking recovering the container-test is useful to run other tests on the container by overwriting `--entrypoint` with something like `/bin/bash`. WDYT?

**Comment by hangyan** [comment]
seems not much test we have to put in the container now.

**Comment by hangyan** [comment]
I'm gonna merge this for now. If any good test idea come up later, please open a new PR

**Review by hangyan — APPROVED** [review]

**Comment by namusyaka** [comment]
Will do, thanks @hangyan !

**Pull request merged**
