### PR TITLE
GitHub Actions Part2

### PR DESCRIPTION
**Pull request by namusyaka**

### CODE REVIEW

**Comment by namusyaka** [comment]
Hmm, coveralls seems broken (0%). Will take a look in a few days.

**Comment by namusyaka** [comment]
Also, please remove the travis-ci status check.
travis-ci status check example

**Review by hangyan — APPROVED** [review]

**Comment by hangyan** [comment]
Looks great ! Thanks!

**Comment by hangyan** [comment]
> Also, please remove the travis-ci status check.
> travis-ci status check example

@cdrage

**Comment by hangyan** [comment]
> Hmm, coveralls seems broken (0%). Will take a look in a few days.

No rush ,i will look into it too.

**Comment by namusyaka** [comment]
@hangyan Fixed by https://github.com/kubernetes/kompose/pull/1356/commits/7c114896efbf6945473e79c896c83c408860c9af.
Log: https://github.com/kubernetes/kompose/pull/1356/checks?check_run_id=1442879984
Coveralls: https://coveralls.io/jobs/71166186

@cdrage As hangyan mentioned, could you switch the required status check from travis ci to github actions?

**Pull request merged**
