### PR TITLE
1.19.0 Release

### PR DESCRIPTION
**Pull request by cdrage**

### CODE REVIEW

**Comment by cdrage** [comment]
Another release @hangyan ! :)

**Comment by hangyan** [comment]
@cdrage Ah. You are back?

**Comment by cdrage** [comment]
@hangyan Yup. I have some free time now that the project I was working on has been released. I'll just be cleaning up some of the super-high-priority issues.

**Comment by hangyan** [comment]
@cdrage Sure. You can assign some tasks to me and checkout the pending PRs

**Pull request merged**
