### PR TITLE
Add some deprecated info warning

### PR DESCRIPTION
**Pull request by xianlubird**
```
kompose convert --replication-controller
Flag --replication-controller has been deprecated, use --controller
```
Add deprecated info in help message

### CODE REVIEW

**Comment by xianlubird** [comment]
@hangyan @cdrage Is this necessary ?

**Comment by cdrage** [comment]
This helps. LGTM.

**Comment by xianlubird** [comment]
@cdrage @hangyan 
Anyone cloud help to merge this pr ?

**Comment by hangyan** [comment]
@xianlubird The user guide need update too.

**Comment by xianlubird** [comment]
@hangyan Done

**Comment by hangyan** [comment]
@xianlubird Please check again, there are still some occurrences in the user guide doc

**Comment by xianlubird** [comment]
@hangyan yes, nice catch.  I have changed code, thanks.

**Pull request merged**
