### PR TITLE
support multiple containers in a pod

### PR DESCRIPTION
**Pull request by tk42**
As is mentioned in #1012, ```kompose convert``` creates each service as its own pod with single container. 

```--multiple-container-mode``` enables creating multiple containers in a pod. This function is experimental.

In case that such many changes might destroy the behavior known as before, so a temporary argument ```--multiple-container-mode``` switches its behavior. If the argument wasn't specified, kompose converts your docker-compose.yml along with keeping the behavior before. If no problems are reported after released as stable, this development mode is better to be merged for readable codes.

## How it works
In your docker-compose.yml, add ```kompose.service.group={identifier grouped by pods}``` in ```labels``` to specify the containers in the same pod.
```yaml
version: "3"

services:
  nginx:
    image: nginx
    depends_on:
      - logs
    labels: 
      - kompose.service.group=sidecar
    environment:
      - HOGE=TEST
    volumes:
      - "/var/log/nginx"

  logs:
    image: busybox
    command: ["sh","-c","while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done"]
    labels: 
      - kompose.service.group=sidecar
    env_file:
      - .env
    volumes:
      - "/var/log/nginx"
```

add ```--multiple-container-mode``` option in ```kompose convert```
```
kompose convert docker-compose.yml --multiple-container-mode
```

then, you'll get a yaml for deployment as follows

```.yaml
apiVersion: v1
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.service.group: sidecar
      creationTimestamp: null
      labels:
        io.kompose.service: sidecar
      name: sidecar
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: sidecar
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.service.group: sidecar
          creationTimestamp: null
          labels:
            io.kompose.service: sidecar
        spec:
          containers:
            - env:
                - name: HOGE
                  value: TEST
              image: nginx
              name: nginx
              resources: {}
              volumeMounts:
                - mountPath: /var/log/nginx
                  name: nginx-claim0
            - args:
                - sh
                - -c
                - while true; do cat /var/log/nginx/access.log /var/log/nginx/error.log; sleep 30; done
              env:
                - name: HOGEHOGE
                  valueFrom:
                    configMapKeyRef:
                      key: HOGEHOGE
                      name: env
              image: busybox
              name: logs
              resources: {}
              volumeMounts:
                - mountPath: /var/log/nginx
                  name: logs-claim0
          restartPolicy: Always
          volumes:
            - name: nginx-claim0
              persistentVolumeClaim:
                claimName: nginx-claim0
            - name: logs-claim0
              persistentVolumeClaim:
                claimName: logs-claim0
    status: {}
  - apiVersion: v1
    data:
      HOGEHOGE: TEST
    kind: ConfigMap
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sidecar-env
      name: env
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: logs-claim0
      name: logs-claim0
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
kind: List
metadata: {}
```

### CODE REVIEW

**Comment by hangyan** [comment]
@tk42 You can follow the links and sign the CLA

**Comment by tk42** [comment]
@hangyan 
I signed up a CLA account and received its verification with email as well.
I found my commits contained wrong user.name in git config so I forced push those commits in correct user.name, but still failed. I have no clue.

**Comment by hangyan** [comment]
cla seems works now

**Comment by hangyan** [comment]
@tk42 This looks great, i'm reviewing this when i'm free. You may need to update related docs about this change(https://github.com/kubernetes/kompose/blob/master/docs/user-guide.md, the `Labels` part)

**Comment by hangyan** [comment]
Looks all good!

**Comment by hangyan** [comment]
Thanks @tk42. This is great

**Comment by tk42** [comment]
Thanks for the reviewing:bow:

**Comment by joaoborsoi** [comment]
--multiple-container-mode option is not at the user user guide

For me, it would be greate if the kompose.service.export could be used to setup multiples rules on the ingress config

**Comment by hangyan** [comment]
Yeah， will update the docs...

**Comment by tpanza** [comment]
@tk42 is it intended for `--multiple-container-mode` to not work when using `--provider openshift`?

**Comment by tk42** [comment]
> @tk42 is it intended for `--multiple-container-mode` to not work when using `--provider openshift`?

No it's not. In this PR `transformer` is located at pkg/transformer/kubernetes.

**Pull request merged**
