### PR TITLE
Fix ImageStream tags in openshift provider mode

### PR DESCRIPTION
**Pull request by sbs2001**
Fixes https://github.com/kubernetes/kompose/issues/1457.

### CODE REVIEW

**Comment by hangyan** [comment]
Seems a new CLA checker has been added by the k8s team

**Comment by hangyan** [comment]
I have actully checked the code change which introduces the change, but i dont figure out what caused this change

**Comment by sbs2001** [comment]
@hangyan  this https://github.com/kubernetes/kompose/commit/525b68f027295de0d1c1f6fddbcb2b521ae20ca8#diff-32335cd9eadbe75ab331b6dca3742fefc11b61fdb93ff758b05f65d378fd701f caused the issue.

**Comment by hangyan** [comment]
> @hangyan this [525b68f#diff-32335cd9eadbe75ab331b6dca3742fefc11b61fdb93ff758b05f65d378fd701f](https://github.com/kubernetes/kompose/commit/525b68f027295de0d1c1f6fddbcb2b521ae20ca8#diff-32335cd9eadbe75ab331b6dca3742fefc11b61fdb93ff758b05f65d378fd701f) caused the issue.

resource version change?

**Comment by hangyan** [comment]
Looks good. I'm gonna merge this

**Pull request merged**
