### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by jonyhy96**
typo fix
```release-note
None
```

### CODE REVIEW

**Comment by hangyan** [comment]
@jonyhy96  Since this PR is very similar to #980, can you merge the commits and only open one PR, there is no need to create seperate PRs.

**Comment by jonyhy96** [comment]
@hangyan 
Thansk for your reply and i will close the other PR.

**Comment by hangyan** [comment]
@jonyhy96 Since you have create a PR to fix the `initialize` typo, can you fix all the same typo that appears in the code ?

**Comment by jonyhy96** [comment]
@hangyan 
I think i already fix all the initialize typo in this code.
Please help me to specify where the same typo is and i will correct it.
Thx.

**Comment by hangyan** [comment]
```
github.com/kubernetes/kompose ∙ grep "initialize" -R * |grep -v vendor                                                                                           130 ↵ ᚴ master 3≡
Binary file kompose matches
pkg/app/app.go:		// Create/Init new OpenShift object that is initialized with a newly
pkg/transformer/openshift/openshift.go:// initImageStream initialize ImageStream object
pkg/transformer/openshift/openshift.go:// initDeploymentConfig initialize OpenShifts DeploymentConfig object
pkg/transformer/openshift/openshift.go:	// initialize OpenShift Client
pkg/transformer/kubernetes/kubernetes.go:// InitRC initializes Kubernetes ReplicationController object
pkg/transformer/kubernetes/kubernetes.go:// InitSvc initializes Kubernetes Service object
pkg/transformer/kubernetes/kubernetes.go:// InitConfigMap initialized a ConfigMap object
pkg/transformer/kubernetes/kubernetes.go:// InitD initializes Kubernetes Deployment object
pkg/transformer/kubernetes/kubernetes.go:// InitDS initializes Kubernetes DaemonSet object
pkg/transformer/kubernetes/kubernetes.go:// CreatePVC initializes PersistentVolumeClaim
pkg/transformer/kubernetes/kubernetes.go:// InitPod initializes Kubernetes Pod object
```

@jonyhy96

**Comment by jonyhy96** [comment]
@hangyan 
Thanks for your help.
I will fix this as soon as possible.
Hope one day i can be a great coder just like you.:D

**Comment by jonyhy96** [comment]
@hangyan
I think i already fix all initialize typo.How do you think?

**Comment by hangyan** [comment]
looks good. you can merge all the commits into one and a little suggestion: also fix the commit message. (you can check this article: https://chris.beams.io/posts/git-commit/)

**Comment by jonyhy96** [comment]
@hangyan 
Thanks for your help!You are really a nice person!
I'm still a newbie on this and i wll watch out this in the future!:D

**Comment by cdrage** [comment]
Thanks all :+1: This LGTM too!

**Comment by hangyan** [comment]
Wouldn't be better for him to merge the commits before we merge this PR.

**Comment by cdrage** [comment]
Woops. I didn't catch that. My mistake! I should of pressed the "merge commits" button. But yes, it should of been merged into one.

**Pull request merged**
