### PR TITLE
add support for golangci-lint

### PR DESCRIPTION
**Pull request by remyleone**

### CODE REVIEW

**Comment by hangyan** [comment]
The lint ci failed

**Comment by remyleone** [comment]
@hangyan fixed. I've commented on some linters that would take a bit of time to be fixed. Feel free to explore them and judge whether or not they are worth it.

**Comment by remyleone** [comment]
You can also check all the available linters with `golangci-lint linters` and see if you want to include new ones.

**Comment by hangyan** [comment]
I think the current set is good enough. There is no need to consider all sub linters at first, we can work on it later

**Review by hangyan — APPROVED** [review]

**Pull request merged**
