### PR TITLE
support build with docker cli

### LINKED ISSUE #1483: --build does not use BuildKit
I'm trying to use `kompose covert --build` to convert a `docker-compose.yml` with `build` directives in it, but I'm running into problems because some of my images require BuildKit and `kompose convert` doesn't seem to use it.

```
❯ kompose -v convert --build local
...
DEBU Created temporary file /var/folders/bd/9pp6gtps3llfmybfqrx_9k640000gp/T/kompose-image-build-2865844734 for Docker image tarballing
DEBU Image agent build output:
Step 1/19 : FROM rust:latest as builder
 ---> 715d10ea5d71
Step 2/19 : RUN --mount=type=cache,target=$CARGO_HOME/registry,id=cargo-registry,sharing=locked cargo install sccache
FATA Unable to build Docker image for service agent: Unable to build image. For more output, use -v or --verbose when converting.: the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
```

I've tried setting it in my Docker Engine JSON, I've tried exporting `DOCKER_BUILDKIT=1` beforehand, and I've tried prepending the `kompose` command with `DOCKER_BUILDKIT=1`. None of them seem to work.

`docker-compose build` works, so I know I can use BuildKit; it just seems like `kompose convert` doesn't have a way to do it. Is there something I'm missing?

Running on MacOS 12.2.1, Kompose 1.26.1, Docker Desktop 4.5.0 (Docker Engine 20.10.12)

### PR DESCRIPTION
**Pull request by tg123**
fix #1483

same as https://docs.docker.com/compose/reference/envvars/#compose_docker_cli_buildx
call docker cmd to build image instead of docker api to enable buildkit

### CODE REVIEW

**Comment by hangyan** [comment]
Hi, can you check the ci results first?

**Comment by tg123** [comment]
i thought it is due to ci broken
seems some pkg can't be found?

**Comment by cdrage** [comment]
Sorry about the delay @tg123

Do you mind rebasing the PR so the CI can run again? There's been a few changes since the last commit to this PR so I'd like to make 100% it works well.

**Comment by tg123** [comment]
> Sorry about the delay @tg123
> 
> Do you mind rebasing the PR so the CI can run again? There's been a few changes since the last commit to this PR so I'd like to make 100% it works well.

done

**Review by cdrage — APPROVED** [review]
Honestly, I'm okay with this reverting to the CLI if it's possible. It'll help a lot in terms of building the images and the constant changes to the build API which is hard to maintain / keep up.

LGTM.

**Pull request merged**
