### PR TITLE
delete excess code

### PR DESCRIPTION
**Pull request by xichengliudui**
delete excess code

### CODE REVIEW

**Comment by surajssd** [comment]
@hangyan why do you think so? Can provide some justification as to why?

**Comment by hangyan** [comment]
@surajssd There are no style guide saying which one is recommended or not. Thave have the same effect. This is no need to create a PR to change this, except that we need to make a rule for this project and change all the  occurrences.

**Comment by surajssd** [comment]
@hangyan is you run golint on the code you will find that the PR does make sense:

```bash
$ golint pkg/loader/compose/utils.go 
pkg/loader/compose/utils.go:137:10: if block ends with a return statement, so drop this else and outdent its block
```

**Comment by xichengliudui** [comment]
@surajssd   Why no merger?

**Comment by hangyan** [comment]
@surajssd Sorry, I have forget to check this. But still, i think may be `golint` is wrong about this(https://github.com/golang/lint/issues/17). For now, we need to follow the rules.

**Pull request merged**
