### PR TITLE
Add support for file based secret

### PR DESCRIPTION
**Pull request by jvitor83**
_Related to issue #296 and PR #1007_ 

Support for:
- Short syntax
- Long syntax
  - Absolute path

_Based on work from @hangyan_.
_As asked by @cdrage at https://github.com/kubernetes/kompose/pull/1007#issuecomment-425939217_

### CODE REVIEW

**Comment by alanjds** [comment]
cc: @henriquegibin
See also: https://github.com/kubernetes/kompose/issues/296#issuecomment-375955367

**Comment by jvitor83** [comment]
@hangyan @janetkuo @kadel 
Any news about this PR?

**Comment by hangyan** [comment]
my apologize, will review this from now

**Comment by hangyan** [comment]
test_stdin failed, this is a long exist issue, can be ignored for now.

**Comment by ChanderG** [comment]
@hangyan The new `secrets` related test also seems to have failed: https://travis-ci.org/kubernetes/kompose/jobs/619127981#L1121.

**Comment by hangyan** [comment]
That's wired, i'm sure i only see a stdin test failed for this PR.. @ChanderG would you mind to fix this tests and i will review this ASAP? This will help us a lot

**Comment by ChanderG** [comment]
Working on a fix.

**Comment by ChanderG** [comment]
@hangyan , have opened a PR #1198.

**Comment by ChanderG** [comment]
@hangyan , just to confirm stdin_test always fails? 
But from my understanding so far, though it fails, the overall tests should always pass / have the CI return a green tick.

**Pull request merged**
