### PR TITLE
Support tcp/http liveness/readiness probe

### LINKED ISSUE #1427: HTTP/TCP liveness/readiness probe generation
Is there a way to generate HTTP/TCP readiness/liveness probe as opposed to readiness/liveness command?

### PR DESCRIPTION
**Pull request by ichxxx**
close #1427 

Add extra labels to support tcp liveness/readiness probe and http readiness probe 
```yaml
kompose.service.healthcheck.liveness.tcp_port: 8080
kompose.service.healthcheck.readiness.http_get_path: /ready
kompose.service.healthcheck.readiness.http_get_port: 8080
kompose.service.healthcheck.readiness.tcp_port: 8080
```

### CODE REVIEW

**Comment by hangyan** [comment]
> And I find the annotations have a bit problem on multiple containers, that annotations just show info about one of the services, not all the services.

What do you mean? Would you like to give an example?

**Comment by ichxxx** [comment]
> > And I find the annotations have a bit problem on multiple containers, that annotations just show info about one of the services, not all the services.
> 
> What do you mean? Would you like to give an example?

For example:
**docker-compose.yaml**
```yaml
version: "3.3"
services:
  mongo:
    image: mongo
    labels:
      kompose.service.group: "my-group"
      kompose.service.healthcheck.liveness.tcp_port: 8080

  mysql:
    image: mysql
    labels:
      kompose.service.group: "my-group"
      kompose.service.healthcheck.liveness.tcp_port: 8081
```
**output-k8s.json**
```json
{
  "kind": "Deployment",
  "apiVersion": "apps/v1",
  "metadata": {
    "name": "my-group",
    "annotations": {
      "kompose.service.group": "my-group",
      "kompose.service.healthcheck.liveness.tcp_port": "8081"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "annotations": {
          "kompose.service.group": "my-group",
          "kompose.service.healthcheck.liveness.tcp_port": "8080"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "mongo",
            "livenessProbe": {
              "tcpSocket": {
                "port": 8080
              }
            }
          },
          {
            "name": "mysql",
            "livenessProbe": {
              "tcpSocket": {
                "port": 8081
              }
            }
          }
        ]
      }
    }
  }
}
```
There are two serivces, I specify liveness probe by labels. 
The tcp port of  `mongo` service's liveness probe is `8080`, and `mysql` service is `8081`.
But the label info in annotations just show one of the services.

**Comment by hangyan** [comment]
We can create some sperate PRs to fix this. Does not seems a big issues for me now. I guess there are some issues exist for the service group feature.

**Review by hangyan — APPROVED** [review]

**Comment by hangyan** [comment]
Thanks @ichxxx

**Pull request merged**
