### PR TITLE
add fish shell support

### PR DESCRIPTION
**Pull request by top**
sorry I've not tested, but it should be working now.

### CODE REVIEW

**Comment by hangyan** [comment]
@top These is no test case for this issue. Could you provider a working screenshot for you fix?

**Comment by top** [comment]
OK I'll update my changes later.

**Comment by top** [comment]
Screen Shot 2021-08-09 at 11 56 53
Screen Shot 2021-08-09 at 11 57 12
Screen Shot 2021-08-09 at 11 57 32

I think I've fixed support for fish shell.

**Comment by hangyan** [comment]
@top  You need to sign the CLA.

**Comment by hangyan** [comment]
@top Please see the check details, the CLA is still not complete

**Comment by top** [comment]
I'll close this PR and do it again later.

**Pull request closed without merging**
