### PR TITLE
[WiP] adopt Compose-go to parse Compose files v2 or v3

### PR DESCRIPTION
**Pull request by ndeloof**
This PR replace use of deprecated libcompose to adopt compose-spec/compose-go when parsing Compose files v2 or v3.

### CODE REVIEW

**Comment by hangyan** [comment]
@ndeloof Is there any new progress?

**Comment by ndeloof** [comment]
sorry, burned all my spare time on compose v2 maintenance, haven't been able to look further into this one

**Comment by mrangjunboon2017s** [comment]
okay.

**Pull request closed without merging**
