### PR TITLE
Add kompose.image-pull-secret and kompose.image-pull-policy

### PR DESCRIPTION
**Pull request by kiela**
This PR is a rebase of #1040 on top of the latest `master`.

### CODE REVIEW

**Comment by cdrage** [comment]
Hey @kiela are you able to rebase?

**Comment by kiela** [comment]
Sure thing @cdrage!

**Comment by kiela** [comment]
Hi @cdrage, any chance to get this merged in?

**Comment by cdrage** [comment]
@kiela No changes to the code! This looks great. Thanks for your contribution.

I should have a release pushed for next week :100:

**Pull request merged**
