### PR TITLE
OpenShift tests for docker compose v3

### PR DESCRIPTION
**Pull request by ashetty1**
Adding OpenShift tests for docker compose v3 support on Kompose

Ref: #600

### CODE REVIEW

**Comment by cdrage** [comment]
LGTM. Unfortunately because of my distro I can't test this. Could someone else do a quick test?

**Comment by surajnarwade** [comment]
I found following results:

```
Running tests for docker compose v3


Running kompose up ...

INFO We are going to create OpenShift DeploymentConfigs, Services for your Dockerized application. 
If you need different kind of resources, use the 'kompose convert' and 'oc create -f' commands instead. 
 
INFO Deploying application in "myproject" namespace 
INFO Successfully created Service: redis          
INFO Successfully created Service: web            
INFO Successfully created DeploymentConfig: redis 
INFO Successfully created ImageStream: redis      
INFO Successfully created DeploymentConfig: web   
INFO Successfully created ImageStream: web        

Your application has been deployed to OpenShift. You can run 'oc get dc,svc,is' for details.

Waiting for the pods to come up ...

FAIL: kompose up has failed to bring the pods up
the server doesn't have a resource type "deploy"

Testing  restart: 'always' in v3 docker-compose file


Running kompose up ...

INFO We are going to create OpenShift DeploymentConfigs, Services for your Dockerized application. 
If you need different kind of resources, use the 'kompose convert' and 'oc create -f' commands instead. 
 
INFO Deploying application in "myproject" namespace 
INFO Successfully created Service: pival          
INFO Successfully created DeploymentConfig: pival 
INFO Successfully created ImageStream: pival      

Your application has been deployed to OpenShift. You can run 'oc get dc,svc,is' for details.
PASS: restart option set to 'always' is working as expected
NAME            READY     STATUS    RESTARTS   AGE
pival-1-ropod   1/1       Running   1          9s

Running kompose down ...

INFO Deleting application in "myproject" namespace 
INFO Successfully deleted Service: pival          
INFO Successfully deleted DeploymentConfig: pival 
INFO Successfully deleted ImageStream: pival      

Waiting for the pods to go down ...

PASS: All pods are down now. kompose down successful.
NAME            READY     STATUS        RESTARTS   AGE
pival-1-ropod   1/1       Terminating   1          13s
the server doesn't have a resource type "deploy"
Makefile:62: recipe for target 'test-openshift' failed
make: *** [test-openshift] Error 1
```

**Comment by ashetty1** [comment]
@surajnarwade Buildconfig tests are failing due to #521 changes; the tests added here are working.

**Comment by cdrage** [comment]
@ashetty1 what changes? I don't believe we've updated anything related to buildconfig since then.

@surajnarwade can you try again?

**Comment by ashetty1** [comment]
@cdrage the change in examples/buildconfig/docker-compose.yml

**Comment by surajnarwade** [comment]
@cdrage okay

**Comment by ashetty1** [comment]
@cdrage Could you take a look at this too.

**Comment by surajnarwade** [comment]
@ashetty1 , I just tried this PR, I think  `kompose down` is needed, as it says  `FATA Error while deploying application: services "redis" already exists 
` 
and results:

```
Running tests for environment variable for docker compose v3


Running kompose up ...

INFO We are going to create OpenShift DeploymentConfigs, Services for your Dockerized application. 
If you need different kind of resources, use the 'kompose convert' and 'oc create -f' commands instead. 
 
INFO Deploying application in "myproject" namespace 
FATA Error while deploying application: services "redis" already exists 
FAIL: kompose up has failed
the server doesn't have a resource type "deploy"

Running tests for docker compose v3


Running kompose up ...

INFO We are going to create OpenShift DeploymentConfigs, Services for your Dockerized application. 
If you need different kind of resources, use the 'kompose convert' and 'oc create -f' commands instead. 
 
INFO Deploying application in "myproject" namespace 
FATA Error while deploying application: services "redis" already exists 
FAIL: kompose up has failed
the server doesn't have a resource type "deploy"
```

**Comment by ashetty1** [comment]
@surajnarwade weird. Works for me. Can you just try:

./script/test_in_openshift/run.sh script/test_in_openshift/tests/v3-redis.sh

**Comment by surajnarwade** [comment]
change route to `nip.io` as, 

```
FAIL: Route *.xip.io has not been exposed
```

**Comment by cdrage** [comment]
What's the status of this @ashetty1 ? Perhaps you can rebase against master? :+1:

**Comment by ashetty1** [comment]
@cdrage Apologies. Give me a day. Will follow up on this.

**Comment by ashetty1** [comment]
@cdrage @surajnarwade kindly give it a spin. Have rebased and squashed the commits.

**Comment by cdrage** [comment]
Works with the exception of Docker Compose v3 environment variables test not coming up:
```sh
Running tests for environment variable for docker compose v3


Running kompose up ...

INFO We are going to create OpenShift DeploymentConfigs, Services for your Dockerized application. 
If you need different kind of resources, use the 'kompose convert' and 'oc create -f' commands instead. 
 
INFO Deploying application in "myproject" namespace 
INFO Successfully created Service: redis          
INFO Successfully created Service: web            
INFO Successfully created DeploymentConfig: redis 
INFO Successfully created ImageStream: redis      
INFO Successfully created DeploymentConfig: web   
INFO Successfully created ImageStream: web        

Your application has been deployed to OpenShift. You can run 'oc get dc,svc,is' for details.
No resources found.

Waiting for the pods to come up ...

No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
No resources found.
```

**Comment by ashetty1** [comment]
@cdrage can you try once more and push this?

**Comment by cdrage** [comment]
@ashetty1 works now! Mergin'

**Pull request merged**
