### PR TITLE
concat and merge service fields when merging compose files (#1186)

### PR DESCRIPTION
**Pull request by ChanderG**
As a summary, the following is the break up of the keys specified to be merged/concated:

1. Done and tested
    - Env (merge)
    - Labels (merge)
    - Ports (concat)
    - Volumes (merge by mount dir)
    - Tmpfs (concat) 

2. Done, but not tested/useful (as these are not supported in kompose anyway)
   - DNS (concat)
   - DNS Search (concat)
   - External Links (concat)
   - Expose (concat)

3. Not done as it's not needed
   - Devices (merge)

### CODE REVIEW

**Comment by ChanderG** [comment]
@hangyan ,fyi.

**Comment by hangyan** [comment]
@ChanderG All looks great, thank you very much!

**Comment by ChanderG** [comment]
@hangyan Just noticed that the test I added failed on CI of master, go1.13 build. The same test succeeds on the other 2 builds and on the go1.13 pre-merge PR tests. We may need to investigate.

**Comment by hangyan** [comment]
@ChanderG Yes, i have noticed that, it's very odd. Usually they all fail or succeed. I have use my local kompose done dome convert and checked, it all seems fine. Any ideas?

**Comment by hangyan** [comment]
@ChanderG An occasionally test error on go1.1. gives me some clue, turns out when we merge the volume config, we use a `map`.In golang, the iteration of a map is by random order..So the volumes mount list will not match sometimes.

**Comment by ChanderG** [comment]
@hangyan ,suspected that, did not get time to investigate. Saw your fix. Thanks.

**Pull request merged**
