### PR TITLE
Update dep for compose 3.5+

### PR DESCRIPTION
**Pull request by hangyan**
Finally, i think i managed to update the dependency....

#1119 
#1058

### CODE REVIEW

**Comment by hangyan** [comment]
#1119 #1058

**Comment by cdrage** [comment]
Thanks for this change @hangyan 

Tests pass (travis + semaphore).

This all looks good to me!

**Comment by hangyan** [comment]
@cdrage can you merge this PR?

**Comment by lerit** [comment]
@cdrage  any plan for release a new kompose version for this merged request?

**Comment by marceloavan** [comment]
@lerit @cdrage 
I'm also looking forward for a new version with this PR. But, if there is a _ease_ way to build from source code explained somewhere, I will be happy to try.

**Comment by hangyan** [comment]
@marceloavan Just clone the code and run `make bin`

**Comment by marceloavan** [comment]
@hangyan 

Thank you for your response. I have tried but it was not that easy. I need to do some setup before, I think. I will try with more time later.

**Pull request merged**
