### PR TITLE
change master to main in scripts and docs

### PR DESCRIPTION
**Pull request by cdrage**
change master to main in scripts and docs

Changes the naming from master to main in the scripts and documentation.

Do not merge unless CI passes!

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by cdrage** [comment]
@AhmedGrati I am also disabling 1.18 since staticcheck no longer works with 1.18 with the GitHub actions: https://github.com/dominikh/staticcheck-action

I've also set a specific version for statticcheck to use 2023.1 due to the issues we keep having with CI regarding it.

**Comment by cdrage** [comment]
> I think that issues still persist even if we disable staticcheck

Oooff, see any way to fix it?

**Comment by AhmedGrati** [comment]
In the `Makefile` -> `validate`, if you remove staticcheck I think it works. Can you try it?

**Comment by cdrage** [comment]
> In the `Makefile` -> `validate`, if you remove staticcheck I think it works. Can you try it?

Yeah, statticcheck IMO is causing too many problems at the moment. So I'll go ahead and change it.

**Comment by AhmedGrati** [comment]
@cdrage In our code, we have two packages that require Go with version 1.19, but our CI runs on bot 1.18 and 1.19, so it fails on 1.18 version.

**Comment by cdrage** [comment]
@AhmedGrati with this PR I'm also going to fix CI and just rip statticcheck out. Looks like CI is passing now!

**Review by AhmedGrati — APPROVED** [review]
LGTM

**Pull request merged**
