### PR TITLE
add autocompletion for fish shell

### PR DESCRIPTION
**Pull request by top**
@hangyan

### CODE REVIEW

**Comment by hangyan** [comment]
@top Golang CI failed

**Comment by hangyan** [comment]
@top You can join the slack channel. Read the readme doc to find the link

**Comment by top** [comment]
> @top You can join the slack channel. Read the readme doc to find the link

OK, I found that file I modified was not gofmt-ed automatically by Goland, It should be OK now. @hangyan

**Comment by top** [comment]
> @top You can join the slack channel. Read the readme doc to find the link

gofmt-ed, goimports-ed, golangci-lint-ed and etc. with vscode.

**Comment by hangyan** [comment]
@top Thanks!

**Pull request merged**
