### PR TITLE
Submodule with a 'go get'-friendly url

### LINKED ISSUE #1124: go get failed
```
go get -u github.com/kubernetes/kompose

# cd /Users/montanaflynn/Development/go/src/github.com/kubernetes/kompose; git submodule update --init --recursive
Cloning into '/Users/montanaflynn/Development/go/src/github.com/kubernetes/kompose/build/rpm'...
fatal: repository 'https://src.fedoraproject.org/cgit/rpms/kompose.git/' not found
fatal: clone of 'https://src.fedoraproject.org/cgit/rpms/kompose.git' into submodule path '/Users/montanaflynn/Development/go/src/github.com/kubernetes/kompose/build/rpm' failed
Failed to clone 'build/rpm'. Retry scheduled
Cloning into '/Users/montanaflynn/Development/go/src/github.com/kubernetes/kompose/build/rpm'...
fatal: repository 'https://src.fedoraproject.org/cgit/rpms/kompose.git/' not found
fatal: clone of 'https://src.fedoraproject.org/cgit/rpms/kompose.git' into submodule path '/Users/montanaflynn/Development/go/src/github.com/kubernetes/kompose/build/rpm' failed
Failed to clone 'build/rpm' a second time, aborting
package github.com/kubernetes/kompose: exit status 1
```

### LINKED ISSUE #1126: repository 'https://src.fedoraproject.org/cgit/rpms/kompose.git/' not found
On docker alpine image, running
`GOPATH=/ go get -u github.com/kubernetes/kompose && kompose --help`

gives  :
```
Cloning into '/src/github.com/kubernetes/kompose/build/rpm'...
fatal: repository 'https://src.fedoraproject.org/cgit/rpms/kompose.git/' not found
fatal: clone of 'https://src.fedoraproject.org/cgit/rpms/kompose.git' into submodule path '/src/github.com/kubernetes/kompose/build/rpm' failed
Failed to clone 'build/rpm' a second time, aborting
package github.com/kubernetes/kompose: exit status 1
```

### PR DESCRIPTION
**Pull request by irlevesque**
Fixes #1126 
Fixes #1124

### CODE REVIEW

**Comment by irlevesque** [comment]
CLA was signed last year. Perhaps a Linux Foundation identity issue. Submitted a support request.

**Comment by irlevesque** [comment]
Re-signed CLA

**Comment by hangyan** [comment]
@irlevesque Thanks!

**Pull request merged**
