### PR TITLE
Refactor package app to use const rather than raw string

### PR DESCRIPTION
**Pull request by hangyan**

### CODE REVIEW

**Comment by surajnarwade** [comment]
@hangyan , run `gofmt` try `make test` locally as well

**Comment by hangyan** [comment]
@surajnarwade sorry, i forgot this. Will fix this ASAP.

**Comment by hangyan** [comment]
@surajnarwade CI seems broken for now... can you help me with it ?

**Comment by surajnarwade** [comment]
@hangyan, I have restarted the build :)

**Comment by hangyan** [comment]
@surajnarwade  still, same error

**Comment by hangyan** [comment]
@surajnarwade @cdrage can you review this?

**Comment by cdrage** [comment]
This is a good refactor. Thanks 💯 This LGTM!

**Pull request merged**
