### PR TITLE
Reenable cmd tests

### PR DESCRIPTION
**Pull request by cdrage**
Reenables the cmd tests that were previously always saying PASS when it
wasn't...

Signed-off-by: Charlie Drage <charlie@charliedrage.com>

### CODE REVIEW

**Comment by sergeyshevch** [comment]
I'm not trying to continue and finish work on #1440 so merging this PR will be really helpful. @cdrage If I run it locally, all tests were passed. Maybe someone can review it?

**Comment by sergeyshevch** [comment]
Why this PR is closed? I guess it will be really helpful to get this merged

**Comment by cdrage** [comment]
@sergeyshevch unfortunatley `kompose` spits out the resources unordered. so the cmd tests passing were flakey and passing only *sometimes*, so I gave up. I'll have to revisit this at a later date.

**Comment by sergeyshevch** [comment]
Ok, so maybe we can disable it in the CI process and merge this PR? Then we can run these tests at least locally and be sure that the code works after our changes

**Pull request closed without merging**
