### PR TITLE
feat: migrate from libcompose to compose-go

### LINKED ISSUE #1152: Kompose doesn't work with docker-compose v3.7
When I try to convert a docker-compose file v3.7 to the various files required by kubernetes using Kompose v1.18.0 , I get the message: Version 3.7 of Docker Compose is not supported. Please use version 1, 2 or 3. Isn't it time yet to update the supported versions?

### LINKED ISSUE #1371: Kompose convert fails on depends_on condition: service_healthy
After introducing `condition: service_healthy` in `depends_on` running `kompose convert` fails with
`FATA services.time-slot-hystrix-monitoring.depends_on must be a list` 
```
services:

  time-slot-turbine-stream-service:
    image: "denisbalan/turbine-stream-service"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tulpn | grep LISTEN"]
      interval: 10s
      timeout: 5s
      retries: 5
	  
  time-slot-hystrix-monitoring:
    depends_on:
      time-slot-turbine-stream-service:
        condition: service_healthy
    image: "denisbalan/hystrix-monitoring"
```

### LINKED ISSUE #1464: Allow conversion of compose files where version is omitted
I was unable to convert my compose files. After some investigation it seems like the problem was that I didn't specify version: on top of the file. According to the compose-spec the version property is deprecated.
https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-top-level-element

### LINKED ISSUE #1518: FATA (root) Additional property name is not allowed
getting:
FATA (root) Additional property name is not allowed

for the following compose file:
version: '3.8'

name: t***o**
services:
  m****:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    env_file:
      - .env  
    environment:
      - MIX_ENV=dev
      # - SECRET_KEY_BASE=********
    ports:
      - "4000:4000"
    links:
      - db
    depends_on:
      - db
    networks:
      - back-tier

  db:
    image: postgres:13-bullseye
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back-tier

volumes:
  db-data: {}

networks:
  front-tier: {}
  back-tier: {}  %

### LINKED ISSUE #1523: Kompose doesn't work with 3.9
It used to, but doesn't anymore. It logs :
FATA version 3.9 of Docker Compose is not supported. Please use version 1, 2 or 3

### PR DESCRIPTION
**Pull request by Lctrs**
libcompose has been deprecated since summer 2021 in favor of https://github.com/compose-spec/compose-go. Kompose should now be able to load all versions of compose.

Closes #1523
Closes #1518
Closes #1464
Closes #1152
Closes #1371

### CODE REVIEW

**Comment by Lctrs** [comment]
@cdrage I wanted to reserve the last commit for another PR, but let's try fixing the CI with it :)

**Comment by Lctrs** [comment]
@cdrage should be good now :)

**Comment by cdrage** [comment]
> @cdrage should be good now :)

thank you! out of bandwidth today, but I'll be testing it out tomorrow :)

**Comment by cdrage** [comment]
Absolutely awesome and the code looks great! My only concern is using dominikh/staticcheck for the static checking. Unfortunately the development looks to have slowed down on that side and I much prefer we use `golint` instead.

Any way we can compromise and use `golint` instead? My concern is that dominikh/staticcheck is non-standard as most projects have implemented the official Go lint supported instead.

**Comment by Lctrs** [comment]
If I'm not mistaken, the source code of golint resides here : https://github.com/golang/lint.
The repo is archived, and on the first lines of the README, it is stated that it is frozen and deprecated, and that the suggested replacement is staticcheck.

staticcheck doesn't seem so dead to me as the last commit on their repo (https://github.com/dominikh/go-tools) is from december 9th 2022.

**Comment by cdrage** [comment]
> If I'm not mistaken, the source code of golint resides here : https://github.com/golang/lint. The repo is archived, and on the first lines of the README, it is stated that it is frozen and deprecated, and that the suggested replacement is staticcheck.
> 
> staticcheck doesn't seem so dead to me as the last commit on their repo (https://github.com/dominikh/go-tools) is from december 9th 2022.

You're totally right! I had thought that golint was merged into the go source code, and now that you've brought it up, I'll go ahead and change the other project I'm working on to staticcheck.

After reviewing this code today, I'm happy to merge it! Thanks so much for this awesome work. You've brought Kompose back to 2023.

**Review by cdrage — APPROVED** [review]

**Pull request merged**
