### PR TITLE
add annotations to ingress

### LINKED ISSUE #1071: Labels not converted to annotations in ingress
If you have something like:

```yaml
version: '2'
services:
    web:
        labels:
            kompose.service.expose: dev.example.com
            kompose.service.expose.tls-secret: tls-secret
            kompose.service.type: clusterip

            kubernetes.io/ingress.class: nginx
            certmanager.k8s.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/rewrite-target: /
        ports:
            - '80:80'
```

the annotations related to the ingress controller are not present in the `Ingress` object (they're there in `Service` and `Deployment`).

### PR DESCRIPTION
**Pull request by treksler**
this closes #1071

### CODE REVIEW

**Comment by hangyan** [comment]
@treksler Would you mind sign the CLA first?

**Comment by treksler** [comment]
I signed it

**Comment by cdrage** [comment]
This LGTM

**Comment by cdrage** [comment]
Hi @treksler can you rebase so we can make sure it passes tests?

Many thanks!

**Comment by mikegerber** [comment]
This would be useful for me, as it should fix issue #1071.

**Comment by stevefan1999-personal** [comment]
Reason for reviving: Some specific use case. This is really useful for people like me who combines traefik and kompose to effortlessly convert legacy docker compose services with the use of external-dns, which it unfortunately looks for annotations in ingress kind only, not on deployment, which is the current behavior to convert docker compose labels. 

So I either had to re-patch the ingress router after installing the helm chart created by kompose, or I will have to dump the chart and then patch it inline. Both of them are very tedious.

**Comment by hangyan** [comment]
> Reason for reviving: Some specific use case. This is really useful for people like me who combines traefik and kompose to effortlessly convert legacy docker compose services with the use of external-dns, which it unfortunately looks for annotations in ingress kind only, not on deployment, which is the current behavior to convert docker compose labels.
> 
> So I either had to re-patch the ingress router after installing the helm chart created by kompose, or I will have to dump the chart and then patch it inline. Both of them are very tedious.

Sorry for you to wait so long, i will look into it

**Pull request closed without merging**
