### PR TITLE
Add Dockerfile

### LINKED ISSUE #1045: Add official docker image build
I would like use kompose packaged as a docker image.

https://hub.docker.com/r/femtopixel/kompose/

While this works, it would be nice to either have an official image or at least have this linked in the readme.

### PR DESCRIPTION
**Pull request by spawnia**
Resubmit #1100 with correct user/email

Hey @cdrage

According to your suggestion, i added a simple Dockerfile.

Feel free to modify if you see any fit. Thanks!

Resolves #1045

### CODE REVIEW

**Comment by spawnia** [comment]
Can someone with the appropriate permissions add an automated build to Dockerhub?

**Comment by hangyan** [comment]
@spawnia Sorry i don't have the permissions, @cdrage  seems not available for now...

**Pull request merged**
